---
title: "My Website"
---

This is a template for creating course websites at our department.

The easiest way to create a new website is to create a new Rstudio project, using the Simple Rmarkdown Website template (New project -> New directory -> Simple Rmarkdown Website).

# Project structure

The new project will include four files.

- `_site.yml` is used to set the the overall structure of the website, such as header, theme, font, etc.
- `index.Rmd` will when knitted create the landing page for the website. It has to be named index.Rmd.
- `about.Rmd` is a sample page and can be deleted.
- `*.Rproj` is file holding information about the Rstudio project itself.


See other pages on the navigation bar for more details.

**Important**: Once the project folder is created, go to the `_site.yml` file and add `output_dir: "."` to the top! Otherwise the website will be build inside a wrong folder and won't be easily publishable.

# Website deployment

Once the website is ready, click the *Build Website* button under the the *build* tab in Rstudio (close to the *Environment* tab, where you normally see your imported data, etc.). Make sure all .Rmd file are saved first. All .Rmd files in the root directory will be knitted and the site will be build for you.

Note that you will have to rebuild the site every time you change the navigation bar or otherwise change `_site.yml`. If you are only changing content of an existing page (i.e. an existing .Rmd file), you don't have to rebuild the site, just knit the specific file.

After the website is build, push it to Github. Then go to the website repository and navigate to *Settings* -> *Pages*. There, under the source header, choose which branch of the repository should be published (usually main) and click save. Github should tell you the adress of you new website, e.g. *"Your site is ready to be published at https://sociology-fa-cu.github.io/sample-course-website/"*